# .pages.yml
media:
  # let your editors upload images into public/images
  input: public/images
  output: /images

content:
  # a blog-post collection stored as markdown frontmatter
  - name: posts
    label: Blog Posts
    type: collection
    path: src/content/posts
    format: yaml-frontmatter
    fields:
      - name: title
        label: Title
        type: string
        required: true

      - name: date
        label: Date
        type: date
        required: true

      - name: body
        label: Body
        type: rich-text